def main():
  print("Welcome to the Detective game!")
  print("Choose your character name:")
  character_name = input("Enter your character's name: ")
  print(f"Welcome, {character_name}!")

  # Choose game type
  game_choice = input("Choose a game: (1) Find the Killer Clues, (2) Find the Stolen Car: ")
  if game_choice not in ("1", "2"):
      print("Invalid choice. Please enter 1 or 2.")
      return

  # Find the Killer Clues (Game 1)
  if game_choice == "1":
      print("YOU HAVE TO FIND THE KILLER CLUE SO WE CAN FIND THE KILLER")
      locations = {
          "dining_hall": "The grand dining hall seems undisturbed. Find another area.",
          "kitchen": "Very good detective! You found the first clue: knife prints. Now go find two more clues.",
          "bedroom": "Good! You found footprints of the killer. But whose are they?",
          "garage": "The garage is empty. Find another area to search for clues.",
          "store_room": "Go ahead, you've found a clue in a dusty box!"
      }
      found_clues = []
      attempts = 5  # Adjust difficulty by changing this value (attempts to find clues)

      # Look for clues
      while len(found_clues) < 3 and attempts > 0:
          current_location = input(f"Choose a location (attempts remaining: {attempts}): (dining hall, kitchen, bedroom, garage, store room): ").lower()
          if current_location not in locations:
              print("Invalid location. Please choose from the available options.")
              continue
          print(locations[current_location])
          if current_location in ("kitchen", "bedroom", "store_room") and current_location not in found_clues:
              found_clues.append(current_location)
          attempts -= 1  # Decrement attempts after each location choice

      if attempts == 0:
          print("You ran out of attempts to find clues. Game over!")
          return

      # Combine clues and identify culprit
      combine_clues = input("Do you want to combine the clues together? (yes/no): ").lower()
      if combine_clues == "yes":
          culprits = {"knife prints": ["Mr. Malak", "Mrs. Heera"], "footprints": ["Miss Juhi"]}
          # Option 1: Check for clue existence before accessing
          suspects = set()
          for clue in found_clues:
              if clue in culprits:
                  suspects.update(culprits[clue])

          # Option 2: Use get method with default value
          # suspects = set.union(*[culprits.get(clue, set()) for clue in found_clues])

          # Display the suspects based on the clues found
          print("Based on the clues, the suspects are:", ", ".join(suspects))
          attempts = 3  # Adjust difficulty by changing this value (attempts to identify culprit)
          while attempts > 0:
              culprit = input(f"Who do you think is the killer? (Choose from suspects, attempts remaining: {attempts}): ")
              if culprit in suspects and ("Mrs. Heera" in culprit.lower()):
                  print("Congratulations detective! You found the killer.")
                  return
              else:
                  print("No, this is not the killer. Try again!")
                  attempts -= 1  # Decrement attempts after each guess
                  if attempts == 0:
                      print("You ran out of attempts to identify the culprit. Game over!")
                      return
                  print("Suspects:", ", ".join(suspects))
      else:
          print("Alright, keep searching for more clues.")

  # Find the Stolen Car (Game 2 - Replace with your desired implementation)
  elif game_choice == "2":
      print("This feature is under development. Coming soon!")

  print(f"Thanks for playing, {character_name}!")

if __name__ == "__main__":
  main()
